name: Deploy to Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Prepare files for deployment
      run: |
        # Copy the home page index.html to the root of dist for the main site
        cp dist/src/pages/home/index.html dist/index.html
        # Copy other page HTML files to their respective directories
        mkdir -p dist/meet dist/issues dist/connect dist/endorsements dist/mediakit dist/donate dist/vote
        cp dist/src/pages/meet/index.html dist/meet/
        cp dist/src/pages/issues/index.html dist/issues/
        cp dist/src/pages/connect/index.html dist/connect/
        cp dist/src/pages/endorsements/index.html dist/endorsements/
        cp dist/src/pages/mediakit/index.html dist/mediakit/
        cp dist/src/pages/donate/index.html dist/donate/
        cp dist/src/pages/vote/index.html dist/vote/
      
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 50.6.19.203
        username: info@bradbettencourt.com
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        local-dir: ./dist/
        server-dir: /public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/README.md
          **/.env*
          **/package*.json
          **/tsconfig.json
          **/vite.config.ts
          **/.github/**
          **/src/**
